changelog:
  categories:
  - title: 🚀 Features
    labels:
    - enhancement
    - feature
    - feat
    - Semver-Minor
  - title: 🐛 Bug Fixes
    labels:
    - bug
    - fix
    - Semver-Patch
  - title: 💥 Breaking Changes
    labels:
    - breaking-change
    - Semver-Major
    - break
  - title: 📚 Documentation
    labels:
    - documentation
    - docs
  - title: 🔧 Maintenance
    labels:
    - maintenance
    - refactor
    - chore
  - title: Other Changes
    labels:
    - "*"
