name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  VERSION: ${{ github.ref_name }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RELEASE_NAME: "valheim-backup-script"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build
        run: go build -o valheim-backup-script main.go
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            valheim-backup-script
          tag: ${{ env.VERSION }}
          title: ${{ env.VERSION }}
          generate_release_notes: true
          draft: false
